# Generated by Django 2.2.1 on 2019-05-27 14:01

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_mentorpage_mentortitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='简介'),
        ),
    ]
