# Generated by Django 2.2.1 on 2019-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20190527_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorindexpage',
            options={'verbose_name': '老师列表页', 'verbose_name_plural': '老师列表页'},
        ),
        migrations.AlterModelOptions(
            name='mentorpage',
            options={'verbose_name': '老师详情页', 'verbose_name_plural': '老师详情页'},
        ),
        migrations.AlterModelOptions(
            name='mentortagindexpage',
            options={'verbose_name': '师资队伍页', 'verbose_name_plural': '师资队伍页'},
        ),
    ]
