# Generated by Django 2.2.1 on 2019-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190527_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsindexpage',
            options={'verbose_name': '资讯列表页', 'verbose_name_plural': '资讯列表页'},
        ),
        migrations.AlterModelOptions(
            name='newspage',
            options={'verbose_name': '资讯详情页', 'verbose_name_plural': '资讯详情页'},
        ),
        migrations.AlterModelOptions(
            name='newstagindexpage',
            options={'verbose_name': '热点资讯页', 'verbose_name_plural': '热点资讯页'},
        ),
    ]
