# Generated by Django 2.2.1 on 2019-05-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_auto_20190530_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineepage',
            name='age',
            field=models.CharField(default='保密', max_length=8, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='traineepage',
            name='occupation',
            field=models.CharField(default='自由职业者', max_length=16, verbose_name='职业'),
        ),
    ]
