# Generated by Django 2.2.1 on 2019-05-25 10:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190514_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='body',
            field=wagtail.core.fields.StreamField([('标题', wagtail.core.blocks.CharBlock(classname='full title')), ('段落', wagtail.core.blocks.RichTextBlock()), ('图片', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
