# Generated by Django 2.2.1 on 2019-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190525_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='category',
            field=models.CharField(choices=[('faculty', '师资培训'), ('workshop', '名师工作坊')], default='workshop', max_length=16, verbose_name='课程类别'),
        ),
    ]
