# Generated by Django 2.2.1 on 2019-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190530_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': '课程详情页', 'verbose_name_plural': '课程详情页'},
        ),
    ]
