# Generated by Django 2.2.1 on 2019-05-28 17:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonepage',
            name='body',
            field=wagtail.core.fields.StreamField([('milestone_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('time', wagtail.core.blocks.DateBlock()), ('event', wagtail.core.blocks.CharBlock()), ('direction', wagtail.core.blocks.ChoiceBlock(choices=[('left', '向左'), ('right', '向右')]))])))]),
        ),
    ]
