# Generated by Django 2.2.1 on 2019-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_cobranchpagegalleryimage_contactuspagegalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranchpage',
            name='route',
            field=models.CharField(blank=True, max_length=256, verbose_name='交通路线'),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='route',
            field=models.CharField(blank=True, max_length=256, verbose_name='交通路线'),
        ),
    ]
