# Generated by Django 2.2.1 on 2019-05-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0006_auto_20190529_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuspage',
            old_name='route',
            new_name='traffic_route',
        ),
    ]
