# Generated by Django 2.2.1 on 2019-05-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_auto_20190529_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactuspage',
            options={'verbose_name': '联系我们', 'verbose_name_plural': '联系我们'},
        ),
    ]
