# Generated by Django 2.2.1 on 2019-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0009_auto_20190529_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranchpage',
            name='latitude',
            field=models.FloatField(default=24.47439, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='cobranchpage',
            name='longitude',
            field=models.FloatField(default=118.104776, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='latitude',
            field=models.FloatField(default=24.47439, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='longitude',
            field=models.FloatField(default=118.104776, verbose_name='经度'),
        ),
    ]
