# Generated by Django 2.2.1 on 2019-05-30 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0010_auto_20190530_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusindexpage',
            options={'verbose_name': '关于我们总览页', 'verbose_name_plural': '关于我们总览页'},
        ),
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': '关于我们页', 'verbose_name_plural': '关于我们页'},
        ),
        migrations.AlterModelOptions(
            name='classroompage',
            options={'verbose_name': '学习环境页', 'verbose_name_plural': '学习环境页'},
        ),
        migrations.AlterModelOptions(
            name='cobranchindexpage',
            options={'verbose_name': '合作机构列表页', 'verbose_name_plural': '合作机构列表页'},
        ),
        migrations.AlterModelOptions(
            name='cobranchpage',
            options={'verbose_name': '合作机构详情页', 'verbose_name_plural': '合作机构详情页'},
        ),
        migrations.AlterModelOptions(
            name='contactusindexpage',
            options={'verbose_name': '联系我们列表页', 'verbose_name_plural': '联系我们列表页'},
        ),
        migrations.AlterModelOptions(
            name='milestonepage',
            options={'verbose_name': '发展历程页', 'verbose_name_plural': '发展历程页'},
        ),
    ]
