# Generated by Django 2.2.1 on 2019-05-29 10:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cert_id', models.CharField(max_length=32, unique=True, verbose_name='证书编号')),
                ('user_name', models.CharField(max_length=32, verbose_name='证书持有人姓名')),
                ('user_id', models.CharField(max_length=64, unique=True, verbose_name='证书持有人身份证')),
                ('issue_date', models.DateField(auto_now=True, verbose_name='证书颁布事件')),
                ('category', models.CharField(choices=[('NORMAL', '普通瑜伽教练认证'), ('SENIOR', '高级瑜伽教练认证')], default='NORMAL', max_length=16, verbose_name='证书类别')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '瑜伽教练证书',
                'verbose_name_plural': '瑜伽教练证书',
                'db_table': 'Certificate',
            },
        ),
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='发表日期')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, max_length=128, verbose_name='简介')),
                ('body', wagtail.core.fields.StreamField([('标题', wagtail.core.blocks.CharBlock(classname='full title')), ('段落', wagtail.core.blocks.RichTextBlock()), ('图片', wagtail.images.blocks.ImageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HelpPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=256, verbose_name='图片说明')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='缩略图')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='certificate.HelpPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HelpPageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=256, verbose_name='文档说明')),
                ('doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='证书相关文档')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='certificate.HelpPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
