# Generated by Django 2.2.1 on 2019-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='category',
        ),
        migrations.AddField(
            model_name='cert',
            name='program',
            field=models.CharField(blank=True, max_length=64, verbose_name='培训项目'),
        ),
    ]
