# Generated by Django 2.2.1 on 2019-05-29 13:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('certificate', '0002_auto_20190529_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertQueryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(auto_now_add=True, verbose_name='发表日期')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, max_length=128, verbose_name='简介')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
