# Generated by Django 2.2.1 on 2019-05-29 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0003_certquerypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True, verbose_name='简介')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RenameModel(
            old_name='HelpPage',
            new_name='CertHelpPage',
        ),
        migrations.RenameModel(
            old_name='HelpPageDocument',
            new_name='CertHelpPageDocument',
        ),
        migrations.RenameModel(
            old_name='HelpPageGalleryImage',
            new_name='CertHelpPageGalleryImage',
        ),
    ]
