# Generated by Django 2.2.1 on 2019-05-29 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20190529_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 29, 15, 12, 45, 108966), verbose_name='证书颁布事件'),
        ),
    ]
