# Generated by Django 2.2.1 on 2019-05-29 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_auto_20190529_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='证书颁布事件'),
        ),
    ]
