# Generated by Django 2.2.1 on 2019-05-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_auto_20190529_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certhelppage',
            options={'verbose_name': '证书帮助页', 'verbose_name_plural': '证书帮助页'},
        ),
        migrations.AlterModelOptions(
            name='certindexpage',
            options={'verbose_name': '证书列表页', 'verbose_name_plural': '证书列表页'},
        ),
        migrations.AlterModelOptions(
            name='certquerypage',
            options={'verbose_name': '证书查询页', 'verbose_name_plural': '证书查询页'},
        ),
    ]
